title: PFSINHC
description: Welcome to the Presidio Field Station Interactive Natural History Collection's online presence. 
theme: just-the-docs

url: https://benanlam.github.io/PFSINHC

nav_order:
  - index.md
  - loans.md
  - volunteer.md

callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: blue

aux_links:
  Field Station Website: https://presidio.gov/explore/attractions/field-station
